chattore:
  discord:
    botToken: "nou"
    serverId: 1234
    channelId: 1234
  irc:
    name: "ORENetwork"
    server: "irc.esper.net"
    channel: "#openredstone"
    password: "nou"
  format:
    global: "%prefix% &7| &e%sender%&7: &r%message%"
    message_received: "&6[&c%sender% &6->&c me&6]&r %message%"
    message_sent: "&6[&cme &6->&c %recipient%&6]&r %message%"
    me: "* &o%sender% %message% &r*"
    social_spy: "&6[&c%sender% &6->&c %recipient%&6]&r %message%"
    command_spy: "&6%sender%: %message%"
    error: "&c&lOh NO ! &7: &c%message%"
    chattore: "&6[&cChattORE&6] &c%message%"
    help: "&6[&cHelp&6]&c %sender%&7: &r%message%"
